### ISSUE TITLE
Import all tasks at the top level?

### ISSUE THREAD

**Issue by mhvk** [mhvk/baseband-tasks#106]
It seems to make little sense to have to import the tasks from a given module, except perhaps the helpers and `io`. Just import them all at the top level?

**Comment by mhvk** [comment]
Or should things be gathered in, say, `tasks.py` so that it makes more sense as a submodule for baseband (`baseband_tools`).

**Comment by luojing1211** [comment]
Are we limiting ourselves for the baseband data only? I believe we can do filterbank as well

**Comment by mhvk** [comment]
> I believe we can do filterbank as well

Ah, yes, good point!

The name remains the most difficult part!!

**Comment by mhvk** [comment]
Done by having the `baseband.tasks` plugin system.
