### ISSUE TITLE
Give frequency via the function task

### ISSUE THREAD

**Issue by luojing1211** [mhvk/baseband-tasks#120]
Do we encourage setting the frequency at the downstream? Currently, it does not. 

```
from baseband import vdif
from scintillometry.functions import Square

data_dir = '/hdd/vidf_data/test_vidf/0001'
files = [os.path.join(data_dir, '0001{0:03d}.vdif'.format(n)) for n in range(50)]
ih = vdif.open(files, sample_rate = 400 * u.MHz / 1024)
sq = Square(ih)
sq .frequency = np.linspace(400, 800, 1024)
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-6be8f97d068f> in <module>()
      1 sq = Square(ih)
----> 2 sq.frequency = np.linspace(400, 800, 1024)

AttributeError: can't set attribute

**Comment by mhvk** [comment]
So far, I've allowed passing in `frequency` (etc.) for all tasks where it made obvious sense. Arguably, we could just allow it for any task, but right now the idea is that one would use the [`base.SetAttribute`](https://scintillometry.readthedocs.io/en/latest/api/scintillometry.base.SetAttribute.html#scintillometry.base.SetAttribute) - really, we need some basic getting started instructions!

I'm not super-keen on allowing it to be set after the fact; I think it is cleaner if the task handles are immutable.

**Comment by luojing1211** [comment]
I also like to make the idea to set it from on the source. Maybe we can raise a message saying: "please set frequency from the source."

**Comment by mhvk** [comment]
Yes, you're right, the error message should tell what to do (refer to `SetAttribute`, I think).

**Comment by mhvk** [comment]
Hmm, coming back to this after a while: the error message currently is not under our control, since `frequency` is a property. We would have to define a `@frequency.setter` just for raising a more informative error message...  I think it makes more sense instead to focus on getting some simple tutorials up...
