### ISSUE TITLE
Easies way to update my local branch to baseband-tasks

### ISSUE THREAD

**Issue by luojing1211** [mhvk/baseband-tasks#191]
If I just do fetch and rebase, I don't think the package name is updated. Should I have a new folk of the repository?

**Comment by mhvk** [comment]
No need to have a new fork. If you rebase on master, you should have the new inner directory to `baseband_tasks`. I think you can even rebase most branches and have them automatically take into account the new names (except for new files, perhaps).

Also, you can change the remote using `git remote set-url`.

If you want to have the outer directory changed (i.e., the one inside which the git repository resides), you do have to do that yourself: `cd ..; mv scintillometry baseband-tasks`.

Happy to chat/check via a screen share if that helps.
