### ISSUE TITLE
Phase __str__() doesn't always return a string

### ISSUE THREAD

**Issue by theXYZT** [mhvk/baseband-tasks#216]
This is a minor bug. But the `__str__` method in the `Phase` class does not necessarily return a string, but can return an `ndarray` of strings.

Here's an example that should throw a TypeError:

```python
y = Phase([1.2, 1.8, 2.0])
print(y)
```

https://github.com/mhvk/baseband-tasks/blob/master/baseband_tasks/phases/phase.py#L315-L316

**Comment by mhvk** [comment]
Currently, returns an array, should instead typeset like `Quantity`, i.e., something like
```
y = Phase([1.2, 1.8, 2.0])
y.to_string()
Out[36]: array(['1.19999999999999996', '1.8', '2.0'], dtype='<U19')
In [45]: str(u.Quantity(y.value, u.cycle))
Out[45]: '[1.2 1.8 2. ] cycle'
```

**Comment by theXYZT** [comment]
Also, `_repr_latex_` is broken!

**Comment by mhvk** [comment]
Just a note for later solution: part of the problem is that `np.array2string` ignores the formatter for structured dtype. Eventually would need actual override, as in https://github.com/astropy/astropy/pull/11127/files#diff-5e55811608c2eb3eca0430d6120ab1e4cf52fc928327f0f4c8c1d3d3953c0169R853
