### ISSUE TITLE
pytest input

### ISSUE THREAD

**Issue by luojing1211** [mhvk/baseband-tasks#230]
@mhvk I just got this problem. Should I install some more packages?
$ pytest tests/test_sampling.py 
ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: --doctest-rst
  inifile: /home/jingluo/Projects/baseband-tasks/setup.cfg
  rootdir: /home/jingluo/Projects/baseband-tasks

**Comment by mhvk** [comment]
Easiest to test is with `tox -e test`. Alternatively, `pip -e .[test]` and then run `pytest`. See https://baseband.readthedocs.io/en/stable/install.html#testing-the-installation (which only mentions the latter, so a bit out of date)
