### ISSUE TITLE
Stack giving unreadable shape when samples_per_frame != 1

### ISSUE THREAD

**Issue by Seraf-N** [mhvk/baseband-tasks#240]
[stack_test.zip](https://github.com/mhvk/baseband-tasks/files/7694369/stack_test.zip)

**Comment by mhvk** [comment]
@Seraf-N - in your script, you use `sideband=1`, but for CHIME data that should be sideband=-1 (since the channels are ordered inversely too).

This is not a small effect:
```
In [36]: from baseband_tasks.dm import DispersionMeasure

In [37]: dm = DispersionMeasure(71.02227638 * u.pc / u.cm**3)

In [38]: dm.time_delay(400.*u.MHz, (400+400/1024)*u.MHz).to(u.ms)
Out[38]: <Quantity 3.59212789 ms>
```
So, with the wrong sideband, you smear the signals the wrong way inside each channel by 7 ms at the bottom of the band!

**Comment by mhvk** [comment]
p.s. Do check whether you are making the same mistake for the Crab in your standard script! (It is recoverable... but needs good bookkeeping).

**Comment by mhvk** [comment]
Of course, none of this is related to the error you are getting!

**Comment by mhvk** [comment]
I got no errors with current master, so think #234 solved it. Will close this issue now. Hope to have a new baseband-task version out soon.
